### DISCUSSION TITLE
How to use categories in keep?

### DISCUSSION THREAD

**Discussion by qqwqqw689** [XPoet/hexo-theme-keep#217] [General]
How to use categories in keep?

**Comment by XPoet** [comment]
Steps:
1. create`categories` page
   ```sh
   hexo new page categories
   ```
2. enable`categories` link in `_config.yml`
    ```yaml
    menu:
      Home: /
      Archives: /archives
      # Tags: /tags
      Categories: /categories
      # Links: /links
      # About: /about
      # Changelog: /changelog
      # ......
    ```
