### DISCUSSION TITLE
求助：文章内的标题都靠右对齐了

### DISCUSSION THREAD

**Discussion by LuXugang** [XPoet/hexo-theme-keep#331] [Q&A] [answered]
大佬你好，我从3.7升级到4.1.3后，调整了配置文件：
```yml
## ======================================================================================
## Hexo Theme Keep
## Documents: https://keep-docs.xpoet.cn
## Repository: https://github.com/XPoet/hexo-theme-keep
## ======================================================================================

# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/base_info.html
# ---------------------------------------------------------------------------------------
base_info:
  title: Lu Xugang的小屋
  author: Lu Xugang
  primary_color: "#0066cc"
  logo: /images/koala.jpg
  favicon: /images/logo.svg
  avatar: /images/luxugang.jpg
first_screen:
  enable: true # Option values: true | false
  header_transparent: true # Option values: true | false
  background_img: /images/bg.svg
  description: 明月几时有 把酒问青天||不知道天上宫阙 今夕是何年
  hitokoto: false      # Option values: true | false
scroll:
  progress_bar: true # Option values: true | false
  percent: false       # Option values: true | false
menu:
  首页: /
  归档: /archives
  标签: /tags
  分类: /categories
  关于: /about

# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/social_contact.html
# ---------------------------------------------------------------------------------------
social_contact:
  enable: true # Option values: true | false
  links:
    # Fill in your social platform links here, e.g. `github: https://github.com/XPoet`
    # If you want to click open the picture, you need to add a prefix `img | `,
    # at the same time change your link to the image link.
    github:          https://github.com/LuXugang
    weixin:          #img | /images/wechat.jpg
    qq:              # QQ
    weibo:           # WeiBo
    zhihu:           # ZhiHu
    twitter:         https://twitter.com/luxugang87
    facebook:        # Facebook
    email:           luxugang@apache.org

# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/home.html
# ---------------------------------------------------------------------------------------
home:
  # Website announcement in home page
  announcement: 文章内的标题怎么都靠右对齐显示了，这是什么情况？ # Announcement content, Can be null

  # Show category in home page post block
  category: true           # Option values: true | false

  # Show tags in home page post block
  tag: true                # Option values: true | false

  # Set the datetime type of home page post block
  post_datetime: created    # Option values: updated | created
  post_datetime_format: YYYY-MM-DD HH:mm:ss


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/post.html
# ---------------------------------------------------------------------------------------
post:
  # Author badge in the post
  author_badge:
    enable: true         # Option values: true | false

    # If true, show Lv1, Lv2, Lv3 ...
    # If false, show custom badge
    level_badge: true    # Option values: true | false

    # Custom badge array, You can be fill one or more item
    custom_badge: ["One", "Two", "Three"]

  # Post word count
  # Depend on Hexo Plugin: hexo-wordcount (`npm install hexo-wordcount`)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    wordcount: true # Word count, one article. Option values: true | false
    min2read: false # Time to read, one article. Option values: true | false
  # Post datetime
  datetime_format: "YYYY-MM-DD HH:mm:ss"  # Datetime format. e.g. "YYYY-MM-DD HH:mm:ss"

  # Post copyright info
  copyright_info: false # Option values: true | false

  # Post share
  share: true  # Option values: true | false

  # Reward author
  reward:
    enable: true # Option values: true | false
    img_link: /images/buymeacoffee.jpg            # Image link for the payment QR code
    text:       Buy me a coffee        # Custom reward text, Can be null


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/code_block.html
# ---------------------------------------------------------------------------------------
code_block:
  # Toolbar include: "code copy", "code block collapse" and "code language"
  tools:
    enable: true            # Option values: true | false
    style: mac           # Option values: default | mac
  highlight_theme: obsidian   # Option values: default | obsidian


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/toc.html
# ---------------------------------------------------------------------------------------
toc:
  enable: true # Option values: true | false

  # Automatically add list number to toc
  number: true # Option values: true | false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false  # Option values: true | false

  # If true, auto open TOC every time when you enter the article page
  init_open: true # Option values: true | false

  # TOC layout on article page
  layout: left # Option values: left | right


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/website_count.html
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true # Option values: true | false
    site_uv: true # Option values: true | false
    site_pv: ture # Option values: true | false
    page_pv: true # Option values: true | false


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/local_search.html
# Depend on Hexo Plugin: hexo-generator-searchdb (`npm install hexo-generator-searchdb`)
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true # Option values: true | false
  preload: true # Preload the search data when the page loads. Option values: true | false


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/comment.html
# ---------------------------------------------------------------------------------------
comment:
  enable: true # Option values: true | false
  use: giscus # Option values: valine | gitalk | twikoo | waline | giscus

  # Valine
  # See: https://github.com/xCss/Valine
  #      https://valine.js.org
  valine:
    appid:           # Your leancloud application appid
    appkey:          # Your leancloud application appkey
    server_urls:     # Your Server URL
    placeholder:     # Input box placeholder

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  #      https://gitalk.github.io
  gitalk:
    github_id:     luxugang   # GitHub repo owner
    github_admins:    # GitHub Admins (in Array type), optional
    repository:    luxugang-comments   # Repository name to store issues
    client_id:     854bbd89fef1537d3af5   # GitHub Application Client ID
    client_secret: dc309b20e38535d86307f485f575855a93bf766b   # GitHub Application Client Secret
    proxy:            # GitHub oauth request reverse proxy for CORS

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  #      https://twikoo.js.org
  twikoo:
    env_id:          # Environment ID
    region:          # Environment region, Can be null
    version: 1.6.36  # Twikoo version, default use v1.6.36

  # Waline
  # See: https://github.com/walinejs/waline
  #      https://waline.js.org/guide/get-started.html
  waline:
    server_url:         # Server URL
    reaction: false     # Post reactions, option values: true | false
    version: 3.2.1      # Waline version, default use v3.2.1

  # Giscus
  # See: https://github.com/giscus/giscus
  #      https://giscus.app
  # Please generate your configuration items in https://giscus.app
  giscus:
    repo: LuXugang/luxugang.github.io
    repo_id: R_kgDdfDSOKY7V7g
    category: Announcements    # Recommend use Announcements
    category_id: DC_kDKY7sdfV7s4CaCS9
    reactions_enabled: false # Option values: true | false

  # Artalk
  # See: https://github.com/ArtalkJS/Artalk
  #      https://artalk.js.org
  artalk:
    server:                    # Server URL

  # Disqus
  # See: https://disqus.com/
  disqus:
    shortname:                 # Disqus Shortname


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/rss.html
# Depend on Hexo Plugin: hexo-generator-feed (`npm install hexo-generator-feed`)
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false # Option values: true | false


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/lazyload.html
# ---------------------------------------------------------------------------------------
lazyload:
  enable: false # Option values: true | false


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/cdn.html
# ---------------------------------------------------------------------------------------
cdn:
  enable: false # Option values: true | false
  provider: jsdelivr  # Option values: jsdelivr | unpkg

# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/pjax.html
# ---------------------------------------------------------------------------------------
pjax:
  enable: false # Option values: true | false


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/footer.html
# ---------------------------------------------------------------------------------------
footer:
  since: 2018 # The starting year of your website, Can be null
  word_count: true # Option values: true | false

  icp:
    enable: true # Option values: true | false
    record_code: 苏ICP备18064214号-1                     # ICP record code of your website
    url: https://beian.miit.gov.cn   # Your ICP link url, Can be null

  site_deploy:
    enable: true # Option values: true | false
    provider: github     # Option values: github | vercel | netlify | gitee | aliyun | tencent_cloud | upyun
    url:                 # Your deployment provider url, Can be null
  record:
    enable: false        # Option values: true | false
    list:
      - code:            # record code of your website
        link:            # record link of your website, Can be null
      # e.g.
      # - code: ICP 001
      # - link: https://beian.miit.gov.cn


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html
# ---------------------------------------------------------------------------------------
inject:
  enable: false  # Option values: true | false
  css:
    -
    # e.g.
    # - /css/custom-1.css
    # - /css/custom-2.css
    # - ...
  js:
    -
    # e.g.
    # - /js/custom-1.js
    # - /js/custom-2.js
    # - ...

```

然后出现了标题靠右的问题，大佬 您能看出是什么问题吗

<img width="1258" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/6985548/5e53c199-7241-444d-b7d1-55624a80a3bb">
