### ISSUE TITLE
首屏文字接入一言

### ISSUE THREAD

**Issue by lilyblessing** [XPoet/hexo-theme-keep#103]
如果开启首屏的话，这个首屏的文字描述很适合接入一言；如果可以的话，希望能加入一言的功能。

**Comment by XPoet** [comment]
挺不错的想法，已纳入后续开发计划中

**Comment by lesevan** [comment]
一年过去了咋还没加入。

**Comment by XPoet** [comment]
Keep 主题 v3.4.6 已支持该功能，请使用最新版本。

```
npm install hexo-theme-keep@3.4.6
```

```yml
  # First screen style settings
  first_screen:
    enable: true # Option values: true | false

    # First screen background image (You can use local image or image external link)
    background_img: /images/bg.svg

    # If enable hitokoto, first screen description is different every time when you enter the site
    hitokoto:
      enable: true # Option values: true | false
```
