### ISSUE TITLE
关于主页的微信图标

### ISSUE THREAD

**Issue by tai769** [XPoet/hexo-theme-keep#110]
我觉得您可以设置成浮动的图片就是鼠标移到微信那个地方，会出现一个小福窗口，出现微信二维码

**Comment by XPoet** [comment]
该需求已在 `v3.4.9` 实现，请使用最新版本。

只需在图片链接前面加上 `img | ` 即可。

示例：

```yml
social_contact:
  enable: true      # Option values: true | false
  links:
    github: https://github.com/XPoet
    weixin: img | https://cdn.staticaly.com/gh/XPoet/image-hosting@master/FE-Cheerleaders/FEC-QR-Code.3exvhwd3h400.webp
    qq:              # QQ
    weibo:           # WeiBo
    zhihu:           # ZhiHu
    twitter:         # Twitter
    facebook:        # Facebook
    email: i@xpoet.cn
```
