### ISSUE TITLE
分类侧边栏显示问题

### ISSUE THREAD

**Issue by SerokSSR** [XPoet/hexo-theme-keep#13]
如果有多级分类，分类布局似乎会出现问题，比如这样：

![image](https://user-images.githubusercontent.com/64728373/90333183-458c6880-dff6-11ea-9daa-6e42738d28bd.png)

**Comment by XPoet** [comment]
@SerokSSR 目前不支持多级分类，以后会加上

**Comment by XPoet** [comment]
@SerokSSR `v1.2.0`版本已支持多级标题，请下载最新版本使用。

**Comment by wohaoa** [comment]
@XPoet 目前有分类侧边栏了么，怎么配置呢，谢谢

**Comment by XPoet** [comment]
@wohaoa ILS主题最新版本已移除双栏模式，无分类侧边栏，你可以创建单独的`分类`页面和`标签`页面。
或者在首页文章块底部开启分类和标签。

![image](https://user-images.githubusercontent.com/24516169/98320828-adaf8100-201e-11eb-861d-1cef9bbc9372.png)

对应的配置项
```yml
home_article:
  category:
    enable: true      # show category in home page article block
    limit: 3          # max number of categories shown in home page article block
  tag:
    enable: true      # show tags in home page article block
    limit: 5          # max number of tags shown in home page article block
```
