### ISSUE TITLE
设置mac 模式下代码背景

### ISSUE THREAD

**Issue by mashangustc** [XPoet/hexo-theme-keep#132]
主题在mac 模式下代码背景不是暗黑色的，修改如下：
themes/keep/source/css/common/codeblock/copy-code.styl
```css
if (hexo-config('code_copy.style') == 'mac') {
  .highlight-container {
    background: #21252b;
    border-radius: 5px;
    box-shadow: 0 10px 30px 0 rgba(0, 0, 0, .4);
    padding-top: 20px;
    margin-top: 10px;

    &::before {
      background: #fc625d;
      border-radius: 50%;
      box-shadow: 20px 0 #fdbc40, 40px 0 #35cd4b;
      content: ' ';
      height: 12px;
      left: 12px;
      margin-top: -10px;
      position: absolute;
      width: 12px;
    }
  }

  .highlight {
    background-color: #282c34;
    .gutter pre {
      background-color: #282c34;
    }

    .code pre {
      background-color: #282c34;
    }
  }
}
```
