### ISSUE TITLE
希望加入waline评论系统

### ISSUE THREAD

**Issue by GuaiJieYo** [XPoet/hexo-theme-keep#135]
valine太难用了 希望加入waline

**Comment by XPoet** [comment]
好的，后续版本会尽快加上

**Comment by Xhofe** [comment]
催更~

**Comment by XPoet** [comment]
该需求已实现，请使用 Keep 主题最新版本

**Comment by XPoet** [comment]
```yml
comment:
  enable: true
  use: waline 
```
