### ISSUE TITLE
关于首屏模块的描述文字问题

### ISSUE THREAD

**Issue by Lyke2003** [XPoet/hexo-theme-keep#153]
有些图片情况下，描述文字的灰色会让它很不好分辨。请问有什么办法可以更改首屏模块显示文字的色彩吗？

**Comment by Lyke2003** [comment]
而且我根据教程添加了lcons，在网站上不显示。但是那个地方是有链接的（没有图标）。
我加的是`circle-c`和`circle-g`
```
social_contact:
  enable: true
  links:
    circle-c: # your GitHub URL
    #weixin: # your WeChat QR-Code URL
    zhihu: # your ZhiHu URL
    circle-g: # your QQ QR-Code URL
```
