### ISSUE TITLE
hexo设置子目录后 首屏背景无法显示以及点击logo-title跳转错误的问题

### ISSUE THREAD

**Issue by Nieerduo** [XPoet/hexo-theme-keep#157]
采用的是克隆仓库放在themes下并重命名为keep的方式来启用主题的

可能的相关配置
首屏背景不显示：
* /hexo-site/_config.yml
```
...
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://xxx.github.io/blog
root: /blog/
...
theme: keep
...
```
* /hexo-site/themes/keep/_config.yml
```
...
  # First screen
  first_screen:
    enable: true
    background_img: /images/bg.svg # You can use local image or image external link
    description: Keep writing and Keep loving.
...
```
修改background_img为/blog/images/bg.svg才有效

点击logo-title跳转出错的原因，可能是由于下面的代码造成的
* /hexo-site/themes/keep/layout/_partital/header.ejs
```
<div class="left">
      <% if (theme.base_info.hasOwnProperty('logo_img') &&
      theme.base_info.logo_img) { %>
      <a class="logo-image" href="/">
        <%- image_tag(theme.base_info.logo_img) %>
      </a>
      <% } %>
      <a class="logo-title" href="/">
        <%= theme.base_info.title || config.title || 'Keep Theme' %>
      </a>
 </div>
```
尝试的解决方式：
```
 <div class="left">
      <% if (theme.base_info.hasOwnProperty('logo_img') &&
      theme.base_info.logo_img) { %>
      <a class="logo-image" href="<%= config.root  %>">
        <%- image_tag(theme.base_info.logo_img) %>
      </a>
      <% } %>
      <a class="logo-title" href="<%= config.root  %>">
        <%= theme.base_info.title || config.title || 'Keep Theme' %>
      </a>
 </div>
```
