### ISSUE TITLE
code_block settings not work

### ISSUE THREAD

**Issue by evalexp** [XPoet/hexo-theme-keep#183]
I clone this repo on 2022.11.14, and found that some settings not work.
There's the settings:
```yaml
code_block:
  # Toolbar include: "code copy", "code block collapse" and "code language"
  tools:
    enable: enable # Option values: true | false
    style: mac # Option values: default | mac
  highlight_theme: default # Option values: default | obsidian
```
But, it does not work:
![image](https://user-images.githubusercontent.com/72970177/201571505-de6fa582-a335-4c56-bfb5-39a75dc30ee7.png)
Then, I use the setting before:
```yaml
code_copy:
  enable: true
  style: mac
```
It works:
![image](https://user-images.githubusercontent.com/72970177/201571654-6df5e3ba-7041-400e-a0a3-8fdac2ac7992.png)

I think it's a config parse bug and hope would be fixed.
