### ISSUE TITLE
Gitalk proxy

### ISSUE THREAD

**Issue by LUKECLEVER** [XPoet/hexo-theme-keep#189]
希望在Gitalk设置项中新增一个proxy (optional) 项来解决Error: Network Error的情况。
It is hoped to add a proxy (optional) option to Gitalk to resolve the case of _Error: Network Error._
或者也可以通过指定gitalk的配置文件的地址方式实现自定义，而不是从cdn直接加载文件。
Alternatively, you can customize by specifying the address of gitalk's configuration file instead of loading the file directly from the cdn.
![CBWZE4IN0@G$JQ WI7`K X9](https://user-images.githubusercontent.com/60529895/208371660-8983cf47-ad98-48af-8af8-5251825ed800.png)

**Comment by LUKECLEVER** [comment]
webpack:///gitalk.jsx
This file contains the unavailable link
<img width="466" alt="image" src="https://user-images.githubusercontent.com/60529895/208569268-8d53056a-e5e9-4c13-9e07-da0284f05957.png">
The URL configured by the proxy is unavailable. You are advised to set it to user-defined

**Comment by XPoet** [comment]
下个后续版本加上

**Comment by XPoet** [comment]
该配置项已支持，请使用最新版本的 Keep 主题 
> `v3.6.1` 及以上

```yml
  gitalk:
    github_id:
    github_admins:
    repository: 
    client_id: 
    client_secret: 
    proxy:            # GitHub oauth request reverse proxy for CORS
```
