### ISSUE TITLE
文章列表时间展示不对

### ISSUE THREAD

**Issue by WhenCoding** [XPoet/hexo-theme-keep#248]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version 3.7.3 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn/tutorial/get-start/install-theme.html).
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me.

### Expected behavior | 预期行为

每次发布后，所有文章都是使用的最新的时间，比如一分钟前

### Actual behavior | 实际行为

我怀疑使用的是更新时间

### Steps to reproduce the behavior | 重现步骤

正常发布后，就可以复现

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
使用的最新的版本
```

### Hexo Configuration | Hexo 配置

```YAML
正常config
```

### Keep Configuration | Keep 配置

```YAML
正常config
```

### Other Information | 其它信息

正常config

**Comment by WhenCoding** [comment]
确实使用了github的自动部署，配置文件地址如下：https://github.com/WhenCoding/WhenCoding.github.io/blob/main/.github/workflows/pages.yml

**Comment by XPoet** [comment]
使用自动部署就会导致你的 Hexo 项目下所有文件的更新时间被修改为自动部署服务器克隆文件的那一刻时间。

不属于 Keep 主题的 Bug。

针对这个问题，你可以使用作者提供的专属 actions，可以解决这个问题。

GitHub Action: https://github.com/theme-keep/hexo-deploy-github-pages-action

配置文件参考示例：

```yaml
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets. GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: XPoet/xpoet.github.io
          BRANCH: master
```

**Comment by WhenCoding** [comment]
您好，尝试您提供的action，发现并没有触发自动部署，请协助定位一下
https://github.com/WhenCoding/WhenCoding.github.io/actions/workflows/pages.yml

**Comment by XPoet** [comment]
![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/03b7f95b-bf13-4e92-903c-884c0ee069d4)

**Comment by XPoet** [comment]
name: Hexo Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build and Deploy
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_REPOSITORY: WhenCoding/WhenCoding.github.io
          
          
你的配置文件应该这么写

**Comment by WhenCoding** [comment]
好的，我试一下，之前我的action也有这个配置，但是我没有额外替换就可以正常使用，这两个脚本有啥不一样嘛

**Comment by WhenCoding** [comment]
您好，尝试了一下您的方法，action还是无法正常运行，能否帮忙定位一下问题
![image](https://github.com/XPoet/hexo-theme-keep/assets/28731024/70c4fe28-b902-4f6e-a94a-46d6f25d6d85)
使用的是如下的配置
```
name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and Deploy
      uses: theme-keep/hexo-deploy-github-pages-action@master
      env:
        # Your GitHub Token
        PERSONAL_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

        # The repository the action should deploy to
        PUBLISH_REPOSITORY: WhenCoding/WhenCoding.github.io
```

**Comment by XPoet** [comment]
![image](https://github.com/XPoet/hexo-theme-keep/assets/24516169/c099e7b8-5ec3-4f2a-b6a5-0e43a79fecf0)

**Comment by XPoet** [comment]
> ```yaml
> name: Hexo Deploy
> on:
>   push:
>     branches:
>       - main
> 
> jobs:
>   build-and-deploy:
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v3
>         with:
>           fetch-depth: 0
> 
>       - name: Build and Deploy
>         uses: theme-keep/hexo-deploy-github-pages-action@master
>         env:
>           PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>           PUBLISH_REPOSITORY: WhenCoding/WhenCoding.github.io
> ```
> 
> 你的配置文件应该这么写

我已经帮你写好了配置文件，请仔细看！

**${{ secrets.GITHUB_TOKEN }}  要替换成你自己配置的**

**Comment by XPoet** [comment]
```yml
name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and Deploy
      uses: theme-keep/hexo-deploy-github-pages-action@master
      env:
        # Your GitHub Token
        PERSONAL_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

        # The repository the action should deploy to
        PUBLISH_REPOSITORY: WhenCoding/WhenCoding.github.io
```

---

你什么也别改了，复制这份配置
