### ISSUE TITLE
代码块没有正常工作

### ISSUE THREAD

**Issue by TianruiShi** [XPoet/hexo-theme-keep#252]
### Issue Checklist | Issue 检查清单

- [x] I am using Keep version 3.7.3 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn/tutorial/get-start/install-theme.html).
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me.

### Expected behavior | 预期行为

代码块显示复制按钮、代码主题高亮
```yml
# Code block
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/code_block.html
# ---------------------------------------------------------------------------------------
code_block:
  # Toolbar include: "code copy", "code block collapse" and "code language"
  tools:
    enable: true            # Option values: true | false
    style: mac           # Option values: default | mac
  highlight_theme: default   # Option values: default | obsidian
```

### Actual behavior | 实际行为

- 链接到这个问题的演示网站： [发生问题的博客文章](http://localhost:4000/2023/08/28/2023-08-28-node-js-kua-ping-tai-ju-yu-wang-xiao-xi-chuan-shu-yu-qnap-bu-shu-shou-ce/#0x8-%E6%B7%BB%E5%8A%A0%E6%B6%88%E6%81%AF%E4%BB%A3%E7%A0%81%E6%A0%BC%E5%BC%8F%E5%8C%96%E5%92%8C%E6%97%B6%E9%97%B4%E6%88%B3)
- 链接到存储库或源代码的博客：[发生问题博客的仓库](https://gitee.com/StringOD/StringOD)
- 截图：![问题截图](https://pic.imgdb.cn/item/650fec2ac458853aef652af2.jpg)
- 如果截图没加载出来，[点这里看](https://pic.imgdb.cn/item/650fec2ac458853aef652af2.jpg) 不要开科学上网

### Steps to reproduce the behavior | 重现步骤

1. 下载：[有问题的博客示例](https://stringod.lanzoul.com/izf5Q19ot2ne)
2. 安装[Python3](https://www.python.org/)
3. 安装[NodeJS LTS](https://nodejs.org/en)
4. 打开控制台安装Hexo：`npm install hexo-cli -g`
5. 在stringod目录下执行`hexo s`
6. 查看运行后博客页面的代码块

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
v18.12.1
9.7.2
```

### Hexo Configuration | Hexo 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: StringOD
subtitle: '阳光下の少年'
description: ''
keywords:
author: StringOD
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://stringod.gitee.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-keep-master

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: git@gitee.com:StringOD/StringOD.git
  branch: master

# 搜索插件
search:
  path: search.xml
  field: post

# 中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'
  
# emoji表情 【::, :smile】
githubEmojis:
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:

# RSS 订阅支持
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
```

### Keep Configuration | Keep 配置

```YAML
language: zh-CN   # 中文简体
## ======================================================================================
## Hexo Theme Keep v3.7.7
## Preview: https://xpoet.cn
## Documents: https://keep-docs.xpoet.cn
## Repository: https://github.com/XPoet/hexo-theme-keep
## ======================================================================================

# ---------------------------------------------------------------------------------------
# Your basic info
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/base_info.html
# ---------------------------------------------------------------------------------------
base_info:
  # Your blog website title
  title: 阳光下の少年

  # Your blog website author name
  author: StringOD

# ---------------------------------------------------------------------------------------
# Theme style settings
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/style.html
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#0066cc"

  # Your blog website logo image
  # You can use local image, image external link or don't fill
  logo: https://pic.imgdb.cn/item/64950b1e1ddac507cc121a2d.png

  # Favicon (You can use local image or image external link)
  favicon: https://pic.imgdb.cn/item/64950b1e1ddac507cc121a2d.png

  # Avatar (You can use local image or image external link)
  avatar: https://pic.imgdb.cn/item/64950b1e1ddac507cc121a2d.png

  # First screen style settings
  first_screen:
    enable: true  # Option values: true | false

    # Set transparent background for header
    header_transparent: true  # Option values: true | false

    # First screen background image (You can use local image or image external link)
    background_img: /images/bg.svg

    # First screen description
    # You can use the "||" to begin a newline, maximum is two lines.
    description: 随缘应变觉无界，因果循环见自然

    # If enable hitokoto, first screen description is different every time when you enter the site
    hitokoto: false      # Option values: true | false

  # Page scroll style settings
  scroll:
    # Show progress bar in top when page scroll
    progress_bar: true  # Option values: true | false

    # Show percent when page scroll
    percent: true       # Option values: true | false

# ---------------------------------------------------------------------------------------
# Navigation menu
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/menu.html
# ---------------------------------------------------------------------------------------
# If you want to enable Categories and Tags, you need to create categories and tags pages
# e.g. `hexo new page categories` or `hexo new page tags`
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Links: /links
  # About: /about
  # Changelog: /changelog
  # ......

# ---------------------------------------------------------------------------------------
# Home page article block display settings
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/home_article.html
# ---------------------------------------------------------------------------------------
home_article:
  # Show category in home page article block
  category:
    enable: true  # Option values: true | false
    limit: 3       # Max number of categories shown in home page article block
  # Show tags in home page article block
  tag:
    enable: true  # Option values: true | false
    limit: 5       # Max number of tags shown in home page article block

# ---------------------------------------------------------------------------------------
# Post page Settings
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/post.html
# ---------------------------------------------------------------------------------------
post:
  # Author label in the post
  author_label:
    enable: true       # Option values: true | false

    # If true, show Lv1, Lv2, Lv3 ...
    # If false, show custom_label_list
    auto: true    # Option values: true | false

    # Label array item can be fill one or more
    custom_label_list: ["Trainee", "Engineer", "Architect"]

  # Post word count
  # Dependencies: hexo-wordcount (`npm install hexo-wordcount`)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    wordcount: true     # Word count, one article. Option values: true | false
    min2read: true      # Time to read, one article. Option values: true | false

  # Post datetime
  datetime_format: "YYYY-MM-DD HH:mm:ss"  # Datetime format. e.g. "YYYY-MM-DD HH:mm:ss"

  # Post copyright info
  copyright_info: true  # Option values: true | false

# ---------------------------------------------------------------------------------------
# Code block
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/code_block.html
# ---------------------------------------------------------------------------------------
code_block:
  # Toolbar include: "code copy", "code block collapse" and "code language"
  tools:
    enable: true            # Option values: true | false
    style: mac           # Option values: default | mac
  highlight_theme: default   # Option values: default | obsidian

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/toc.html
# ---------------------------------------------------------------------------------------
toc:
  enable: true      # Option values: true | false

  # Automatically add list number to toc
  number: false      # Option values: true | false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false  # Option values: true | false

  # If true, auto open TOC every time when you enter the article page
  init_open: true    # Option values: true | false

  # TOC layout on article page
  layout: left      # Option values: left | right

# ---------------------------------------------------------------------------------------
# Local Search
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/local_search.html
# Dependencies: hexo-generator-searchdb (`npm install hexo-generator-searchdb`)
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true   # Option values: true | false
  preload: true  # Preload the search data when the page loads. Option values: true | false

# ---------------------------------------------------------------------------------------
# Lazyload image
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/lazyload.html
# ---------------------------------------------------------------------------------------
lazyload:
  enable: false  # Option values: true | false

# ---------------------------------------------------------------------------------------
# PJAX
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/pjax.html
# ---------------------------------------------------------------------------------------
pjax:
  enable: true  # Option values: true | false

# ---------------------------------------------------------------------------------------
# Footer settings
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/footer.html
# ---------------------------------------------------------------------------------------
footer:
  since: 2017           # The starting year of your website, Can be null
  word_count: true     # Option values: true | false
```

### Other Information | 其它信息

浏览器： Google Chrome 
系统信息：
```
主机名:           STRINGOD
OS 名称:          Microsoft Windows 11 家庭中文版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     阳光下的少年
注册的组织:       暂缺
产品 ID:          00342-30537-51808-AAOEM
初始安装日期:     2022/12/20, 22:01:12
系统启动时间:     2023/9/17, 17:46:09
系统制造商:       Acer
系统型号:         Predator PH317-55
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 141 Stepping 1 GenuineIntel ~2496 Mhz
BIOS 版本:        Insyde Corp. V1.14, 2022/10/25
Windows 目录:     C:\WINDOWS
系统目录:         C:\WINDOWS\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     32,547 MB
可用的物理内存:   21,107 MB
虚拟内存: 最大值: 39,670 MB
虚拟内存: 可用:   24,133 MB
虚拟内存: 使用中: 15,537 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\STRINGOD
修补程序:         安装了 4 个修补程序。
                  [01]: KB5029921
                  [02]: KB5012170
                  [03]: KB5030219
                  [04]: KB5028756
网卡:             安装了 5 个 NIC。
                  [01]: TAP-Windows Adapter V9
                      连接名:      以太网 2
                      状态:        媒体连接已中断
                  [02]: Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)
                      连接名:      WLAN
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.50.1
                      IP 地址
                        [01]: 192.168.50.33
                        [02]: fe80::b9a1:ea14:72f0:876b
                        [03]: fda9:53fe:a218:4a10:d59e:bfcb:14e9:39cd
                        [04]: fda9:53fe:a218:4a10:11ea:7dcb:dc2a:dc9
                  [03]: Killer E2600 Gigabit Ethernet Controller
                      连接名:      以太网
                      状态:        媒体连接已中断
                  [04]: VMware Virtual Ethernet Adapter for VMnet8
                      连接名:      VMware Network Adapter VMnet8
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.23.254
                      IP 地址
                        [01]: 192.168.23.1
                        [02]: fe80::83ec:e10:a243:a8a5
                  [05]: VMware Virtual Ethernet Adapter for VMnet1
                      连接名:      VMware Network Adapter VMnet1
                      启用 DHCP:   是
                      DHCP 服务器: 192.168.182.254
                      IP 地址
                        [01]: 192.168.182.1
                        [02]: fe80::feb9:15e:9b1b:3f90
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。
```

**Comment by XPoet** [comment]
提供的错误信息和复现步骤非常细致 👍🏻，堪称模范。

经过排查：
1、Keep 主题的代码块工具目前只支持 highlight 方式的代码渲染，你需要在你的 Hexo 配置文件 `_config.yml` 设置：
```yaml
highlight:
  enable: true
  ...
prismjs:
  enable: false
  ...
```
也就是关闭 prismjs，然后执行 `hexo clean && hexo server --open` 运行就可以看到  Mac 样式的代码块了。

2、Mac 样式的代码复制按钮，v3.7.7 确实是不可见，存在异常，作者已修复，在 v3.8.0 更新，近期会发新版本。
