### ISSUE TITLE
表格排版不能横向滚动

### ISSUE THREAD

**Issue by justaLoli** [XPoet/hexo-theme-keep#273]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version 3.8.5 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn).
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me.

### Expected behavior | 预期行为

应该可以横向滚动才对。现在的设置在面对列很多的时候很愚蠢。

### Actual behavior | 实际行为

- Links to demo site with this issue:
- Links to repository or source code of the blog:
- Screenshots:

![CleanShot 2023-11-09 at 19 44 17](https://github.com/XPoet/hexo-theme-keep/assets/92238102/226fda33-59f1-460f-a92f-4ea0d0d1021c)

![CleanShot 2023-11-09 at 19 46 43](https://github.com/XPoet/hexo-theme-keep/assets/92238102/d12a45ac-e5ec-406f-a320-ff9e10c2efaa)

### Steps to reproduce the behavior | 重现步骤

1. 新建博客
2. 写一个有很多很多列的表格
3. 部署，完成。

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
这没有用
v21.1.0
10.2.0
```

### Hexo Configuration | Hexo 配置

```YAML
这没有用
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
```

### Keep Configuration | Keep 配置

```YAML
没有修改。
```

### Other Information | 其它信息

和浏览器与操作系统无关。
