### ISSUE TITLE
links 界面md

### ISSUE THREAD

**Issue by Fierygit** [XPoet/hexo-theme-keep#28]
请问 links 界面的外链 md 怎么写的？ 
两栏链接那行

**Comment by XPoet** [comment]
1. 在你的 `Hexo` 项目的 `source` 文件夹里增加 `_data` 文件夹。
2. 在 `_data` 文件夹里新建 `links.yml` 文件。
3. 在 `links.yml` 里按格式填写友链，格式如下：

   ```yml
   - name: XPoet
     link: https://xpoet.cn/
     description: 所有命运的馈赠，早已在暗中标好价格。
     avatar: https://cdn.jsdelivr.net/gh/XPoet/image-hosting@master/common-use/avatar.jpg

   - name: 不知名艺术家
     link: https://jinzhanqi.com/
     description: love artist, love code.
     avatar: https://s3.ax1x.com/2020/11/17/DVvkB4.jpg

   - name: 月拉风
     link: https://mooncool.net/
     description: 不该错落的蝴蝶，长满紫色的琴键
     avatar: https://mooncool.net/static/imgs/butterfly.jpg
   ```

![image](https://user-images.githubusercontent.com/24516169/101299981-f8672780-386e-11eb-967b-e1785f0b3e8d.png)

![image](https://user-images.githubusercontent.com/24516169/101300019-1896e680-386f-11eb-834d-ae9cd7d95e63.png)
