### ISSUE TITLE
当代码块内代码过长时，无法横向滚动代码块

### ISSUE THREAD

**Issue by ShawJie** [XPoet/hexo-theme-keep#284]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.3` or later. （使用 Keep `4.0.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

当代码块内代码过长时，展开代码块后代码可以左右横向滚动。

代码内容被边缘遮挡，但是无法通过滚动进行被遮挡的代码内容查看
<img width="931" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/16751534/aff33e1f-9bd2-4f23-82f3-e448143a294e">

### Actual behavior | 实际行为

- Links to demo site with this issue (发生问题的文章)[https://shawjie.cn/2021/04/24/spring-dev-tools/]
- Links to source code of the blog with this issue (发生问题的博客仓库)[https://github.com/ShawJie/shawjie.github.io]
- Screenshots（屏幕截图）
<img width="885" alt="image" src="https://github.com/XPoet/hexo-theme-keep/assets/16751534/a7f6bc1b-a4df-45c8-b28c-19171f2ccb84">

### Steps to reproduce the behavior | 重现步骤

1. 创建一个新的Hexo网站
2. 安装Keep主题并针对主题进行简单的配置
3. 输入 `hexo new post anytitle` 创建新的post
4. 在post中编辑行最终高度大于250px且单行较长的代码块
5. `hexo clean && hexo server --open`
6. 预览刚刚编辑的代码块

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
v18.14.1
9.3.1
```

### Hexo Configuration | Hexo 配置

```YAML
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
```

### Keep Configuration | Keep 配置

```YAML
# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/code_block.html
# ---------------------------------------------------------------------------------------
code_block:
  # Toolbar include: "code copy", "code block collapse" and "code language"
  tools:
    enable: true            # Option values: true | false
    style: mac          # Option values: default | mac
  highlight_theme: default   # Option values: default | obsidian
```

### Other Information | 其它信息

浏览器：Chrome - 119.0.6045.199
操作系统： Macos - 13.6 (22G120)
