### ISSUE TITLE
本地或外链图片无法显示

### ISSUE THREAD

**Issue by xueqili02** [XPoet/hexo-theme-keep#291]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

网站中能正常显示头像、logo图片

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
https://xueqili02.github.io/
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
https://github.com/xueqili02/xueqili02.github.io
- Screenshots（屏幕截图）
![0F385F10-64D1-4369-B4BD-CE97E08AF516](https://github.com/XPoet/hexo-theme-keep/assets/36269655/90df5aa5-d1c7-4d1e-9f58-f52f948d5837)

title只显示了文字，无法显示图片。
配置中无论本地图片还是外链都无法显示。[配置文件](https://github.com/xueqili02/xueqili02.github.io/blob/main/themes/hexo-theme-keep/_config.yml)
```
style:
  # Theme primary color
  primary_color: "#0066cc"

  # Your blog website logo image
  # You can use local image, image external link or don't fill
  logo: /images/avatar.jpg # https://i.imgur.com/77CaNz6.jpg

  # Favicon (You can use local image or image external link)
  favicon: https://i.imgur.com/77CaNz6.jpg

  # Avatar (You can use local image or image external link)
  avatar: https://i.imgur.com/77CaNz6.jpg

```

### Steps to reproduce the behavior | 重现步骤

1. First step ...   （第一步 ...）访问网站
2. Second step ...  （第二步 ...）查看头像、logo图片
3. Third step ...   （第三步 ...）图片无法正常显示

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
node v20.10.0
npm 10.2.3
```

### Hexo Configuration | Hexo 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Keep
subtitle: Hexo theme keep quick starter
description: ''
keywords:
author: Keep Team
language: en  # en | zh-CN | zh-TW
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://xueqili02.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
```

### Keep Configuration | Keep 配置

```YAML
base_info:
  # Your blog website title
  title: Xueqi Li

  # Your blog website author name
  author: Xueqi Li

# ---------------------------------------------------------------------------------------
# Theme style settings
# Docs: https://keep-docs.xpoet.cn/tutorial/configuration-guide/style.html
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#0066cc"

  # Your blog website logo image
  # You can use local image, image external link or don't fill
  logo: /images/avatar.jpg # https://i.imgur.com/77CaNz6.jpg

  # Favicon (You can use local image or image external link)
  favicon: https://i.imgur.com/77CaNz6.jpg

  # Avatar (You can use local image or image external link)
  avatar: https://i.imgur.com/77CaNz6.jpg

menu:
  Home: /
  Projects: /projects
  Publications: /publications
  About: /about

social_contact:
  enable: true      # Option values: true | false
  links:
    # Fill in your social platform links here, e.g. [ github: https://github.com/XPoet ]
    # If you want to click open the picture, you need to add a prefix "img |",
    # at the same time change your link to the image link.
    # e.g. [ weixin: img | https://x.com/images/wechat.png ] or [ weixin: img | ./images/wechat.png ]
    github: https://github.com/xueqili02

cdn:
  enable: true       # Option values: true | false
  provider: jsdelivr  # Option values: jsdelivr | unpkg
```
