### ISSUE TITLE
导航栏同时出现两个“首页”

### ISSUE THREAD

**Issue by ChangeSuger** [XPoet/hexo-theme-keep#292]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

导航栏应该只会有一个“首页”

### Actual behavior | 实际行为

在升级 Keep 版本（3.7.3 → 4.0.5）的时候发现的该问题，发现这个问题后直接拿启动模板测试了下，目前的实际行为如下：

1. 不添加字段，或添加 `Home: /` 时符合预期（不论是否切换语言）

```yml
menu:
  Home: /               #新增这一行或不新增
  Archives: /archives
  Tags: /tags
```

2. 添加字段 `首页: /` 后的实际行为不符合预期，具体表现如下（以启动模板为例）：

```yml
menu:
  首页: /               #新增这一行
  Archives: /archives
  Tags: /tags
```

  - **_config.yml** 中的 `language` 字段设置为 `zh-CN` 时：

![zh-CN](https://image-hosting-1312492736.cos.ap-beijing.myqcloud.com/imgs0/202312221833759.png)

  - **_config.yml** 中的 `language` 字段设置为 `en` 时：

![en](https://image-hosting-1312492736.cos.ap-beijing.myqcloud.com/imgs0/202312221834126.png)

### Steps to reproduce the behavior | 重现步骤

1. 直接下载[启动模板](https://github.com/theme-keep/hexo-theme-keep-starter)并安装依赖
2. 在 **source/_data/keep.yml** 文件中新增一行

```yml
menu:
  首页: /               #新增这一行
  Archives: /archives
  Tags: /tags
```

3. 本地启动项目 `npm run server`

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
v18.16.0
9.5.1
```

### Hexo Configuration | Hexo 配置

```YAML
# 值设置为 en 或 zh-CN
language: en  # en | zh-CN | zh-TW
```

### Keep Configuration | Keep 配置

```YAML
menu:
  首页: / # 修改部分只有这一行
  Archives: /archives
  Tags: /tags
  Categories: /categories
```
