### ISSUE TITLE
使用Waline评论，能否在用户评论的时候增加邮件提醒？

### ISSUE THREAD

**Issue by WhenCoding** [XPoet/hexo-theme-keep#293]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.0.5` or later. （使用 Keep `4.0.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

如题

### Other Information | 其它信息

无

**Comment by XPoet** [comment]
Waline 评论插件的邮件提醒功能，你需要按照 Waline 的文档来配置和开启，在 Keep 主题中提供了 options 配置项，支持扩展 Waline 的全部配置。

https://keep-docs.xpoet.cn/basis/configuration-guide/comment.html#options

https://waline.js.org/guide/features/notification.html#%E9%82%AE%E4%BB%B6%E9%80%9A%E7%9F%A5

**Comment by WhenCoding** [comment]
> Waline 评论插件的邮件提醒功能，你需要按照 Waline 的文档来配置和开启，在 Keep 主题中提供了 options 配置项，支持扩展 Waline 的全部配置。
> 
> https://keep-docs.xpoet.cn/basis/configuration-guide/comment.html#options
> 
> https://waline.js.org/guide/features/notification.html#%E9%82%AE%E4%BB%B6%E9%80%9A%E7%9F%A5

尝试了一下并不好使，配置如下：
Keep：3.7.7
Waline配置：
```
  waline:
    server_url: https://comment.mynamecoder.com    # Server URL
    reaction: true # Article reactions, Option values: true | false
    version: 2      # Waline version, default use v2
    options:
      SMTP_SERVICE: 163
      SMTP_USER: xxx@163.com
      SMTP_PASS: xxx
      SMTP_SECURE: true
      SITE_NAME: 程序员小明
      SITE_URL: mynamecoder.com
      AUTHOR_EMAIL: xxx@163.com
```
