### ISSUE TITLE
自动部署失败，提示权限不足

### ISSUE THREAD

**Issue by IdealYth** [XPoet/hexo-theme-keep#310]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

成功部署

### Actual behavior | 实际行为

![Snipaste_2024-03-19_16-17-53](https://github.com/XPoet/hexo-theme-keep/assets/31368993/c6b0c234-a6a2-42be-ad49-5192274d820a)
token变量是正确的，但是提示失败

### Steps to reproduce the behavior | 重现步骤

这是配置文件
```
name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and Deploy
      uses: theme-keep/hexo-deploy-github-pages-action@master
      env:
        # Your GitHub Token
        PERSONAL_TOKEN: ${{ secrets.GITHUBTOKEN }}

        # The repository the action should deploy to
        PUBLISH_REPOSITORY: IdealYth/blog
```

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
正常
```

### Hexo Configuration | Hexo 配置

```YAML
正常配置
```

### Keep Configuration | Keep 配置

```YAML
正常配置
```
