### ISSUE TITLE
Giscus 无法加载

### ISSUE THREAD

**Issue by miranquil** [XPoet/hexo-theme-keep#313]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

Giscus 正常使用

### Actual behavior | 实际行为

- Links to demo site with this issue https://miranquil.com/post/c401b8165e00/
- Links to source code of the blog with this issue  https://github.com/miranquil/ar
- Screenshots（屏幕截图）

![CleanShot 2024-04-01 at 17 52 16@2x](https://github.com/XPoet/hexo-theme-keep/assets/25676311/55c61578-f086-4629-a788-0d5fb8332acf)

控制台报错：

Safari:
![CleanShot 2024-04-01 at 17 52 29@2x](https://github.com/XPoet/hexo-theme-keep/assets/25676311/20447e02-b53d-4b1e-b08a-cbc6abad6eca)

Arc(Chromium):

![CleanShot 2024-04-01 at 18 01 32@2x](https://github.com/XPoet/hexo-theme-keep/assets/25676311/8d0d0c06-8a5f-41c7-ba9a-d700097c32b5)

### Steps to reproduce the behavior | 重现步骤

访问站点即可

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
v16.20.2
9.8.0
```

### Hexo Configuration | Hexo 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 金字塔笼罩下的鱼罐头
subtitle:
description: 祈求，寻找
author: 金字塔之歌
language: en-US
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://miranquil.com
root: /
permalink: post/:hash/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
# highlight:
#   enable: true
#   line_number: true
#   auto_detect: false
#   tab_replace: ''
#   wrap: true
#   hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: git@github.com:miranquil/ar.git
    branch: page

# https://github.com/viko16/hexo-permalink-pinyin
permalink_pinyin:
  enable: true
  separator: "-" # default: '-'
```

### Keep Configuration | Keep 配置

```YAML
# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: Miranquil Garden
  author: Miranquil
  url: https://miranquil.com
  # Theme primary color
  primary_color: "#0066cc"

  # Author avatar, You can use local image path or image link
  avatar: /avatar.jpg

  # Website LOGO, You can use local image path or image link
  logo: /avatar.jpg

  # Website favicon, You can use local image path or image link
  favicon: /avatar.jpg

# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#0066CC"

  # Your blog website logo image
  # You can use local image, image external link or don’t fill
  # logo: /images/logo.svg
  logo:

  # Avatar (You can use local image or image external link)
  avatar: /avatar.jpg

  # Font size, customize font size. (you don't usually have to fill)
  # e.g. font_size: 18px
  font_size:

  # Font family, customize font family. (you don't usually have to fill)
  # e.g. font_family: STKaiti, STSong, STHeiti
  font_family:

  # Favicon (You can use local image or image external link)
  favicon:

  # Article image align position, value: left | center
  article_img_align: left

  # Left side width
  left_side_width: 260px

  # Content area max width
  content_max_width: 920px

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: false # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: false
    background_img: /images/bg.svg # You can use local image or image external link
    description: Keep writing and Keep loving.

    # If you want to customize the first screen font color, you can fill in here (e.g. "#0066CC")
    # Otherwise use the theme default font color
    font_color:

    # If enable hitokoto, first screen description is different every time when you enter the site
    hitokoto:
      enable: false # Option values: true | false

  # Scroll style settings
  scroll:
    progress_bar:
      enable: false
    percent:
      enable: true

# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact:
  enable: true
  links:
    github: https://github.com/miranquil # your GitHub URL
    weixin: # your WeChat QR-Code URL
    qq: # your QQ QR-Code URL
    weibo: # your WeiBo URL
    zhihu: # your ZhiHu URL
    twitter: # your twitter URL
    facebook: # your facebook URL
    email: miranquil@gmail.com # your email

# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  Note: /note
  # About: /about
  # Changelog: /changelog
  # ......

# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home:
  category:
    enable: true # show category in home page article block
  tag:
    enable: true # show tags in home page article block
  post_datetime: updated    # Option values: updated | created

# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
post:
  # Image align position in the post, Option values: left | center
  img_align: left
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    wordcount: false # word count, one article
    min2read: false # time to read, one article

  # Author label
  author_badge:
    enable: false
    # If true, show Lv1, Lv2, Lv3 ...
    # If false, show custom badge
    level_badge: true    # Option values: true | false
    # Custom badge array, You can be fill one or more item
    custom_badge: ["One", "Two", "Three"]

  # Post datetime
  datetime_format: "YYYY-MM-DD HH:mm:ss"  # Datetime format. e.g. "YYYY-MM-DD HH:mm:ss"

  # Post copyright info
  copyright_info: true  # Option values: true | false

  # Post share
  share: false           # Option values: true | false

code_block:
  # Toolbar include: "code copy", "code block collapse" and "code language"
  tools:
    enable: true            # Option values: true | false
    style: mac           # Option values: default | mac
  highlight_theme: default   # Option values: default | obsidian

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

  # If true, open TOC every time when you enter the article page
  init_open: false

  # TOC layout on post page
  layout: right      # Option values: left | right


# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: false
    site_uv: false
    site_pv: false
    page_pv: false

# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true
  preload: false # Preload the search data when the page loads

# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: true
  use: giscus

  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    appid: d1KhKhlbXdwPOvTr8nDAVU96-gzGzoHsz # your leancloud application appid
    appkey: HTNn6DaX90N0i5crIPgymV3a # your leancloud application appkey
    placeholder: Do not do evil. # your placeholder

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: # GitHub repo owner
    repository: # Repository name to store issues
    client_id: # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    env_id: # Tencent Cloud environment id
    region: # environment region. If select Guangzhou, fill in "ap-guangzhou".

  # Giscus
  # See: https://github.com/giscus/giscus
  #      https://giscus.app
  # Please generate your configuration items in https://giscus.app
  giscus:
    repo: miranquil/ar
    repo_id: MDEwOlJlcG9zaXRvcnkzMjgzNTY0MzM=
    category: Announcements    # Recommend use Announcements
    category_id: DIC_kwDOE5JSUc4CeX0i
    reactions_enabled: true   # Option values: true | false

# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: true

# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: false

# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: false

# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: false

# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/footer.html
# ---------------------------------------------------------------------------------------
footer:
  since: 2019           # The starting year of your website, Can be null
  word_count: false     # Option values: true | false

  icp:
    enable: false                    # Option values: true | false
    record_code:                     # ICP record code of your website
    url: https://beian.miit.gov.cn   # Your ICP link url, Can be null

  site_deploy:
    enable: true        # Option values: true | false
    provider: github     # Option values: github | vercel | netlify | gitee | aliyun | tencent_cloud | upyun
    url:                 # Your deployment provider url, Can be null

  # When the footer style is shields, you can customize the shields configuration
  # See: https://shields.io
  shields_style:
    enable: false        # Option values: true | false
    custom:
      - link_url:        # Your link url, Can be null
        img_url:         # Shields image url
      # e.g.
      # - link_url: https://github.com/XPoet/hexo-theme-keep
      #   img_url: https://img.shields.io/badge/Hexo-Keep%20v3.7.3-blue?style=flat-square&logo=hexo
      # - ...


# ---------------------------------------------------------------------------------------
# Docs: https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html
# ---------------------------------------------------------------------------------------
inject:
  enable: false  # Option values: true | false
  css:
    -
      # e.g.
      # - /css/custom-1.css
      # - /css/custom-2.css
    # - ...
  js:
    -
      # e.g.
      # - /js/custom-1.js
      # - /js/custom-2.js
      # - ...
```

### Other Information | 其它信息

Safari 17.3.1 (19617.2.4.11.12)
MacOS Sonoma 14.3.1 (23D60)
Arc 1.36.0 (48035)
Chromium Engine Version 123.0.6312.87
