### ISSUE TITLE
hexo deploy sftp 到线上服务器，很多文件的大小都是 0，还有就是图标显示不出来

### ISSUE THREAD

**Issue by whh1009** [XPoet/hexo-theme-keep#319]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

hexo deploy 通过 sftp 发布到远程服务器上，public 目录下的全部文件上传到远程服务器上。

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
- Screenshots（屏幕截图）

### Steps to reproduce the behavior | 重现步骤

1. First step ...   （第一步 ...）
2. Second step ...  （第二步 ...）
3. Third step ...   （第三步 ...）

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
node -v && npm -v
v20.10.0
10.2.3
```

### Hexo Configuration | Hexo 配置

```YAML
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.1.1"
  },
  "dependencies": {
    "hexo": "^7.0.0",
    "hexo-all-minifier": "^0.5.7",
    "hexo-deployer-sftp": "^0.4.1",
    "hexo-filter-mathjax": "^0.9.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-searchdb": "^1.4.1",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-migrator-rss": "^1.1.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.2.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-keep": "^4.1.1",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-url-submission": "^2.0.0",
    "hexo-wordcount": "^6.0.1"
  }
}
```

### Keep Configuration | Keep 配置

```YAML
menu:
  home: / || fa-solid fa-home
  archives: /archives || fa-solid fa-box-archive
  tags: /tags || fa-solid fa-tags
  分类: /categories || fa-solid fa-layer-group


# 文章目录配置
toc:
  enable: true # 是否启用 values: true | false
  number: false # 给 TOC 目录结构自动加上数字编号 values: true | false
  expand_all: true # 展开所有目录结构 values: true | false
  init_open: true # 打开文章页时是否自动打开 TOC 目录结构 values: true | false
  layout: right # 用于设置 TOC 目录结构模块的布局位置，默认为 right (右侧) values: left | right

# 用于配置网站的计数功能，内置不蒜子计数
website_count:
  busuanzi_count:
    enable: true # Option values: true | false
    site_uv: true # Option values: true | false
    site_pv: true # Option values: true | false
    page_pv: true # Option values: true | false

# 站内搜索功能
local_search:
  enable: true # Option values: true | false
  preload: true # 使用搜索功能前是否提前进行预加载搜索数据

# 图片懒加载
lazyload:
  enable: true # Option values: true | false

# 页脚配置
footer:
  since: 2021 # The starting year of your website, Can be null
  word_count: true # Option values: true | false

  icp:
    enable: true # Option values: true | false
    record_code: xxxxx # ICP record code of your website
    url: https://beian.miit.gov.cn # Your ICP link url, Can be null

  site_deploy:
    enable: true # Option values: true | false
    provider: aliyun # Option values: github | vercel | netlify | gitee | aliyun | tencent_cloud | upyun
    url: # Your deployment provider url, Can be null


# 自定义样式
inject:
  enable: true
  css:
    - /css/custom.css
    - /css/font.css
```
