### ISSUE TITLE
_config.yml里做了配置但是更新不了

### ISSUE THREAD

**Issue by 3468998** [XPoet/hexo-theme-keep#320]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.0` or later. （使用 Keep `4.1.0` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

希望我做的配置如果正确的情况下能够有相应的功能，如果做错了希望指导我改正

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
- Screenshots（屏幕截图）

### Steps to reproduce the behavior | 重现步骤

1. First step ...   （第一步 ...）
2. Second step ...  （第二步 ...）
3. Third step ...   （第三步 ...）

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
v20.12.2
10.5.0
10.5.0
```

### Hexo Configuration | Hexo 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: yudesoushang
subtitle: '小杨的网站'
description: '个人网站'
keywords:
author: yudesoushang
language: en
timezone: 'Asia/Shanghai'
avatar:  /images/1.jpg
logo: /images/1.jpg
favicon: /images/1.jpg

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yudeyoushang.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

menu:
  home: / || fa-solid fa-home                                  # 首页
  #archives: /archives || fa-solid fa-box-archive       # 归档
  #tags: /tags || fa-solid fa-tags                              # 标签
  categories: /categories || fa-solid fa-layer-group  # 分类
  links: /links || fa-solid fa-link                                # 链接
  about: /about || fa-solid fa-user-graduate            # 关于
  #photos: /photos || fa-solid fa-image                   # 相册

first_screen:
  enable: true        # Option values: true | false
  background_img: /images/bg.svg
  background_img_dark: /images/bg.svg
  description: 人后的苦尚且还能克服||人前的尊严却无比脆弱
  hitokoto: false      # Option values: true | false

post:
  author_badge:
  enable: true
  level_badge: false
  custom_badge: ["炼气", "筑基", "结丹", "元婴", "化神"]

  word_count:
    wordcount: true     # Word count, one article. Option values: true | false
    min2read: true      # Time to read, one article. Option values: true | false

  datetime_format: "YYYY-MM-DD HH:mm:ss"  # Datetime format. e.g. "YYYY-MM-DD HH:mm:ss"

  copyright_info: true  # Option values: true | false

  share: true           # Option values: true | false

  reward:
    enable: true        # Option values: true | false
    img_link:  /images/2.jpg          # Image link for the payment QR code
    text: 感谢大佬打赏！！！               # Custom reward text, Can be null
    img_align: center
  created_datetime_icon: fa-solid fa-star
  updated_datetime_icon: fa-solid fa-arrows-rotate

code_block:
  tools:
    enable: true             # Option values: true | false
    style: mac            # Option values: default | mac
  highlight_theme: default    # Option values: default | obsidian

toc:
  enable: true      # Option values: true | false
  number: false      # Option values: true | false
  expand_all: false  # Option values: true | false
  init_open: true    # Option values: true | false
  layout: right      # Option values: left | right

website_count:
  busuanzi_count:
    enable: true     # Option values: true | false
    site_uv: true    # Option values: true | false
    site_pv: true    # Option values: true | false
    page_pv: true    # Option values: true | false

local_search:
  enable: true      # Option values: true | false
  preload: true     # Preload the search data when the page loads

search:
  path: search.json
  field: post
  content: true
  format: striptags


cdn:
  enable: true       # Option values: true | false
  provider: cdnjs     # Option values: cdnjs | jsdelivr | unpkg

pjax:
  enable: true   # Option values: true | false

footer:
  since: 2024

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:3468998/3768998.github.io.git
  branch: gh-pages
```

### Keep Configuration | Keep 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: yudesoushang
subtitle: '小杨的网站'
description: '个人网站'
keywords:
author: yudesoushang
language: en
timezone: 'Asia/Shanghai'
avatar:  /images/1.jpg
logo: /images/1.jpg
favicon: /images/1.jpg

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yudeyoushang.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

menu:
  home: / || fa-solid fa-home                                  # 首页
  #archives: /archives || fa-solid fa-box-archive       # 归档
  #tags: /tags || fa-solid fa-tags                              # 标签
  categories: /categories || fa-solid fa-layer-group  # 分类
  links: /links || fa-solid fa-link                                # 链接
  about: /about || fa-solid fa-user-graduate            # 关于
  #photos: /photos || fa-solid fa-image                   # 相册

first_screen:
  enable: true        # Option values: true | false
  background_img: /images/bg.svg
  background_img_dark: /images/bg.svg
  description: 人后的苦尚且还能克服||人前的尊严却无比脆弱
  hitokoto: false      # Option values: true | false

post:
  author_badge:
  enable: true
  level_badge: false
  custom_badge: ["炼气", "筑基", "结丹", "元婴", "化神"]

  word_count:
    wordcount: true     # Word count, one article. Option values: true | false
    min2read: true      # Time to read, one article. Option values: true | false

  datetime_format: "YYYY-MM-DD HH:mm:ss"  # Datetime format. e.g. "YYYY-MM-DD HH:mm:ss"

  copyright_info: true  # Option values: true | false

  share: true           # Option values: true | false

  reward:
    enable: true        # Option values: true | false
    img_link:  /images/2.jpg          # Image link for the payment QR code
    text: 感谢大佬打赏！！！               # Custom reward text, Can be null
    img_align: center
  created_datetime_icon: fa-solid fa-star
  updated_datetime_icon: fa-solid fa-arrows-rotate

code_block:
  tools:
    enable: true             # Option values: true | false
    style: mac            # Option values: default | mac
  highlight_theme: default    # Option values: default | obsidian

toc:
  enable: true      # Option values: true | false
  number: false      # Option values: true | false
  expand_all: false  # Option values: true | false
  init_open: true    # Option values: true | false
  layout: right      # Option values: left | right

website_count:
  busuanzi_count:
    enable: true     # Option values: true | false
    site_uv: true    # Option values: true | false
    site_pv: true    # Option values: true | false
    page_pv: true    # Option values: true | false

local_search:
  enable: true      # Option values: true | false
  preload: true     # Preload the search data when the page loads

search:
  path: search.json
  field: post
  content: true
  format: striptags


cdn:
  enable: true       # Option values: true | false
  provider: cdnjs     # Option values: cdnjs | jsdelivr | unpkg

pjax:
  enable: true   # Option values: true | false

footer:
  since: 2024

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:3468998/3768998.github.io.git
  branch: gh-pages
```

### Other Information | 其它信息

火狐和edge，Win11
