### ISSUE TITLE
关于github Action 自动部署时间错乱的问题

### ISSUE THREAD

**Issue by JasonDev324** [XPoet/hexo-theme-keep#334]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.4` or later. （使用 Keep `4.1.4` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

新增的文章在主页的最前面

### Actual behavior | 实际行为

问题博客：
https://jasondev324.github.io/

新增的文章在之前发布的文章之前。
![image](https://github.com/XPoet/hexo-theme-keep/assets/20396159/4cfd6315-56c8-45f9-99b7-a71a6a477bbc)

### Steps to reproduce the behavior | 重现步骤

1. First step ...   obsidian 新增文章
2. Second step ...   文章头部配置了 
```
---
title:  
date: {{ date }}
updated: {{ date }}
tags: 
---
```

4. Third step ...   错乱

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
用的是github action 自动部署
v18.20.3
10.7.0

========
```

### Hexo Configuration | Hexo 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 咩料
subtitle: ''
description: ''
keywords:
author: JasonDev324
language: cn
timezone: ''

# URL

url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked: # 如果原本有就更改下面的这些选项，如果没有就添加
  prependRoot: true
  postAsset: true

relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# keep主题会优先使用其config.yml ,当前文件无效
theme: keep


search:
  path: search.json
  field: post
  content: true
  format: striptags

# Deployment

deploy:
  type: ''
```

### Keep Configuration | Keep 配置

```YAML
home:
  post_datetime: updated    # Option values: updated | created
  post_datetime_format: YYYY年MM月DD日 HH:mm
```

### Other Information | 其它信息

自动部署的workflow

name: 自动部署

on:
  push:
    branches:
      - main

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: false  # 禁用子模块检查
        fetch-depth: 0

    - name: 重置文件时间
      run: find source/_posts -name '*.md' | while read file; do touch -d "$(git log -1 --format="@%ct" "$file")" "$file"; done

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "18"

    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g
        npm install hexo-deployer-git --save
        npm install hexo-wordcount
        npm install hexo-generator-searchdb
        npm install valine --save

    - name: 缓存 Hexo
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: 安装依赖
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
       npm install --save

    - name: 生成静态文件
      run: |
        hexo clean
        hexo generate

    - name: 部署
      run: |
        cd ./public
        git init
        git config --global init.defaultBranch main
        git branch -m main
        git config --global user.name '${{ secrets.HEXO_NAME }}'
        git config --global user.email '${{ secrets.HEXO_EMAIL }}'
        git add .
        git commit -m "Create by workflows"
        git push --force --quiet "https://${{ secrets.HEXO_TOKEN }}@github.com/JasonDev324/JasonDev324.github.io" main:main

        # GitHub配置
