### ISSUE TITLE
希望有双语/多语言的功能 | an optional multi-languages feature support

### ISSUE THREAD

**Issue by carrieeex** [XPoet/hexo-theme-keep#337]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- Detailed description of feature request （功能需求的详情描述）

我希望网站有双语/多语言功能。详见下方网站案例。

- This feature request reference link （功能需求的参考链接）

我在看Hexo/Redefine这个主题的时候发现的例子：支持中英文：[他的第二人生](https://his2nd.life/en/)，还有支持多语言：[SaltyLeo's Blog](https://saltyleo.com)

- This feature request reference screenshots （功能需求的参考截图）

（截屏自以上两个网站）
<img width="1114" alt="Screenshot 2024-07-05 at 10 26 16 PM" src="https://github.com/XPoet/hexo-theme-keep/assets/59303880/a4c563af-c2ec-4da2-911e-fe0f1c73bc0d">
<img width="1097" alt="Screenshot 2024-07-05 at 10 26 48 PM" src="https://github.com/XPoet/hexo-theme-keep/assets/59303880/e0109c6e-1c30-4e39-9ed7-ffe94fe71db7">

### Other Information | 其它信息

可参考：

- 类似的别的主题的issue：[Redefine issue # 334](https://github.com/EvanNotFound/hexo-theme-redefine/issues/334)

- 上面两个网站例子的帖子：[站点双语改造](https://his2nd.life/zh-CN/posts/7a6a6b5a.html#)，[Hexo添加多语言支持「国际化i18n」](https://saltyleo.com/1448.html#)

**Comment by XPoet** [comment]
Keep 主题支持中文简体、中文繁体，英文。

https://keep-docs.xpoet.cn/advanced/set-language.html

你需要先部署一套中文、英文的站点，然后把不同语言的站点链接配置到 menu 导航菜单里面。

示例：
```yaml
menu:
  home: /                       # || fa-solid fa-home
  archives: /archives           # || fa-solid fa-box-archive
  tags: /tags                   # || fa-solid fa-tags
  # categories: /categories     # || fa-solid fa-layer-group
  links: /links                 # || fa-solid fa-link
  # photos: /photos             # || fa-solid fa-image
  tools: /tools                 # || fa-solid fa-tools
  about: /about                 # || fa-solid fa-user-graduate
  英文: fa-solid fa-language || https://xx.com/en # 英文站点
```
