### ISSUE TITLE
能否提供页面访问人次的展示？～

### ISSUE THREAD

**Issue by Olivia98106** [XPoet/hexo-theme-keep#34]
希望作者大大可以在页面左/右/中下角，提供一个页面访问人次的展示，好想看看到底有多少人来了我的博客～

谢谢大大！主题很可爱！

**Comment by XPoet** [comment]
主题有这个功能的，访问人数、总访问量、文章阅读次数
```yml
# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true
```
![image](https://user-images.githubusercontent.com/24516169/103184229-19f98300-48f2-11eb-9399-42df1378182e.png)
