### ISSUE TITLE
Add Google analytics support

### ISSUE THREAD

**Issue by k0baya** [XPoet/hexo-theme-keep#345]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.1.5` or later. （使用 Keep `4.1.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

- Detailed description of feature request （功能需求的详情描述）
- This feature request reference link （功能需求的参考链接）
- This feature request reference screenshots （功能需求的参考截图）

希望可以直接在 `_config.yml` 中添加 Google analytics 的相关参数设置，类似于其他主题的：
```yml
# Google Analytics
google_analytics:
  tracking_id: UA-XXXXXXXXX-X
  localhost_ignored: true
```
