### ISSUE TITLE
Latex渲染

### ISSUE THREAD

**Issue by Wu-Jackie** [XPoet/hexo-theme-keep#372]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

如下Latex语言
$$\frac{b_n}{a_{nn}} \rightarrow b_n$$
渲染成对应的数学公式，在hexo g生成页面后发现页面如下图
![image](https://github.com/user-attachments/assets/6e857e19-f3d1-403a-8fd7-0a0f1d985ae4)

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
因有bug暂未部署
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
```latex
   $$
   \frac{b_n}{a_{nn}} \rightarrow b_n
   $$
```
- Screenshots（屏幕截图）
![image](https://github.com/user-attachments/assets/49134960-fab5-4b03-867e-4e8f698e5169)
如图，经排查后发现katex-html这个是多余的

### Steps to reproduce the behavior | 重现步骤

`实际行为`已排查出结果

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
> node -v
v20.11.0
> npm -v
10.9.0
```

### Hexo Configuration | Hexo 配置

```YAML
mathjax:
  tags: ams               # or 'ams' or 'all'
  single_dollars: true     # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9           # relative CJK char width
  normal_width: 0.6        # relative normal (monospace) width
  append_css: true         # add CSS to every page
  every_page: false        # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of each article
```

### Keep Configuration | Keep 配置

```YAML
keep主题配置未有与issue相关的设置
```

### Other Information | 其它信息

\> npm list
hexo-site@0.0.0 H:\Jackie's Blog
+-- hexo-deployer-git@4.0.0
+-- hexo-filter-mathjax@0.9.0
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-index@3.0.0
+-- hexo-generator-searchdb@1.4.1
+-- hexo-generator-tag@2.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-markdown-it-plus@1.0.6
+-- hexo-renderer-stylus@3.0.1
+-- hexo-server@3.0.0
+-- hexo-theme-landscape@1.0.0
+-- hexo-wordcount@6.0.1
`-- hexo@7.1.1

**Comment by XPoet** [comment]
这个问题跟 Keep 主题没有直接关系，作者无法处理，请尝试更换其他的公式渲染器

**Comment by Wu-Jackie** [comment]
我想是否可以通过js注入等方式将katex-html隐藏而只保留katex-mathml？

**Comment by XPoet** [comment]
可以使用注入 CSS 的方式，隐藏 katex-html

**Comment by i-Nog** [comment]
请问下这个怎么解决的？我也遇到相同问题。

**Comment by Wu-Jackie** [comment]
> 请问下这个怎么解决的？我也遇到相同问题。

参考[文档](https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html)，在你Hexo项目的source目录下新建css目录，所有需要注入的自定义CSS文件都必须存放在source/css/目录下。

其中我的hide.css代码为：

```css
.katex-html {
    display: none !important;
}
```

最后在主题配置文件中的inject模块填入对应参数即可
