### ISSUE TITLE
友链不展示 头像恢复默认的了

### ISSUE THREAD

**Issue by xjzyy** [XPoet/hexo-theme-keep#374]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.3` or later. （使用 Keep `4.2.3` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

展示几个友链

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
- Screenshots（屏幕截图）
实际上很多默认头像
![image](https://github.com/user-attachments/assets/2c543dc6-97d7-4271-b969-2ba33af76729)

### Steps to reproduce the behavior | 重现步骤

1. First step ...   （第一步 ...）
2. Second step ...  （第二步 ...）
3. Third step ...   （第三步 ...）

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
node -v 
v14.18.3

npm -v
6.14.15
```

### Hexo Configuration | Hexo 配置

```YAML
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: keep
```

### Keep Configuration | Keep 配置

```YAML
cat _config.yml 
# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
title: 博客园
author: xjzyy
  url: https://xjzyy.xyz
# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: "#0066CC"

  # Avatar (You can use local image or image external link)
  #avatar: /images/avatar.svg
  #avatar: /images/logo.jpg
  avatar: /images/logo.jpg #本地换CDN
  #avatar: https://cdn.xjzyy.xyz/blog/logo.jpg
  # Favicon (You can use local image or image external link)
  #favicon: /images/logo.svg
  #favicon: /images/logo.jpg
  favicon: /images/bili-favicon.ico

  # Article image align position, value: left | center
  article_img_align: left

  # Left side width
  left_side_width: 260px

  # Content area max width
  content_max_width: 920px

  # Mouse hover
  hover:
    shadow: true # shadow effect when the mouse hover
    scale: true # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: false
    background_img: /images/bg.svg # You can use local image or image external link
    #background_img: https://cdn.xjzyy.xyz/blog/bg.svg #本地换CDN # You can use local image or image external link
    description: Keep writing and Keep loving.

  # Scroll style settings
  scroll:
    progress_bar:
      enable: true
    percent:
      enable: true

# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact:
  enable: false
  links:
    github: https://github.com/xjzyy # your GitHub URL
    #weixin: # your WeChat QR-Code URL
    #qq: # your QQ QR-Code URL
    #weibo: # your WeiBo URL
    #zhihu: # your ZhiHu URL
    #twitter: # your twitter URL
    #facebook: # your facebook URL
    #email: # your email

# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links
  About: /about
  博客园: https://www.cnblogs.com/xjzyy/
  # Changelog: /changelog
  # ......

# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  category:
    enable: true # show category in home page article block
    limit: 3 # max number of categories shown in home page article block
  tag:
    enable: true # show tags in home page article block
    limit: 3 # max number of tags shown in home page article block

# ---------------------------------------------------------------------------------------
# Post page Settings
# ---------------------------------------------------------------------------------------
post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: true
    wordcount: true # word count, one article
    min2read: true # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: false # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: ["代码搬运工","全栈鼓励师","运维工程师","运维老司机","运维架构师"]

# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_copy:
  enable: true
  style: default # values: default | mac

# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: false

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

  # If true, open TOC every time when you enter the article page
  init_open: true

# ---------------------------------------------------------------------------------------
# Post copyright info
# ---------------------------------------------------------------------------------------
copyright_info: # 该配置项用于开启文章内容页的文章版权信息模块.
  enable: true

# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true 
    site_pv: true
    page_pv: true

# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search: #该配置项用于设置网站搜索功能，非常实用，建议开启。开启后，头部导航栏右侧将出现搜索按钮。
  enable: true
  preload: true # Preload the search data when the page loads
#  配置项表示是否在页面加载时预加载搜索数据。
# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: false
  use: valine # values: valine | gitalk | twikoo

  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    appid: # your leancloud application appid
    appkey: # your leancloud application appkey
    placeholder: # your placeholder

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id: # GitHub repo owner
    repository: # Repository name to store issues
    client_id: # GitHub Application Client ID
    client_secret: # GitHub Application Client Secret

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    env_id: # Tencent Cloud environment id
    region: # environment region. If select Guangzhou, fill in "ap-guangzhou".

# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false

# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: false

# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: false

# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: true   # PJAX 开启后，点击页面跳转时，网页顶部会出现彩色进度条。

# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer:
  since: 2019 # the starting year of your website, Can be null
  icp: 苏ICP备18058423号 # ICP record number of your website, Can be null
  upyun: # url

# ---------------------------------------------------------------------------------------
# Keep version (Please don't modify)
# ---------------------------------------------------------------------------------------
#version: 3.4.5
```

### Other Information | 其它信息

友链地址：https://xjzyy.xyz/links/
