### ISSUE TITLE
搜索功能泄露加密文章部分内容

### ISSUE THREAD

**Issue by Pepste2** [XPoet/hexo-theme-keep#385]
### Issue Checklist | Issue 检查清单

- [X] I am using Keep version `4.2.5` or later. （使用 Keep `4.2.5` 或更高版本）
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [X] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

在我认为的正常情况是，全局搜索是不包含隐藏文章内容的
我不知道这算不算是个Bug，在我已知加密文章的部分内容的情况下，尝试用全局搜索功能可以显示一小段内容，如果攻击者不断枚举关键词甚至可以推测整篇文章的内容，当然了这只是我的猜想

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
- https://keep.xpoet.cn/post/f41b05a7b521/
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
- Screenshots（屏幕截图）
![QQ20250110-111139](https://github.com/user-attachments/assets/72278b7f-f897-46dc-a916-964f26b53620)

### Steps to reproduce the behavior | 重现步骤

直接利用全局搜索加密文章关键词即可

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
>node -v
v22.11.0
>npm -v
10.9.0
```

### Hexo Configuration | Hexo 配置

```YAML
##search
search:
  path: search.json
  field: post
  content: true
  format: striptags
```

### Keep Configuration | Keep 配置

```YAML
local_search:
  enable: true   # Option values: true | false
  preload: true  # Preload the search data when the page loads. Option values: true | false
```

### Other Information | 其它信息

浏览器:Chrome 131.0.6778.265
操作系统:Windows11 24H2 26100.2605
