### ISSUE TITLE
在 images 上传 avatar 和 logo 图片后不显示

### ISSUE THREAD

**Issue by rickeygong** [XPoet/hexo-theme-keep#398]
### Issue Checklist | Issue 检查清单

- [x] I am using Keep version `4.2.5` or later. （使用 Keep `4.2.5` 或更高版本）
- [x] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [x] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Expected behavior | 预期行为

1. 在 images 文件夹 上传 avatar.svg 和 logo.svg 
![Image](https://github.com/user-attachments/assets/6a80f05a-7eb8-4205-a45b-e84fd28ff7c6)
2. 依次执行命令：`hexo g` 、 `hexo s` 
3. 本地浏览，未生效（尝试过在无痕模式中打开 http://localhost:4000/）

### Actual behavior | 实际行为

- Links to demo site with this issue （链接到这个 Issue 的演示网站）
- Links to source code of the blog with this issue （链接到这个 Issue 的博客源代码）
- Screenshots（屏幕截图）

### Steps to reproduce the behavior | 重现步骤

1. 在 images 文件夹 上传 avatar.svg 和 logo.svg 
2. 依次执行命令：`hexo g` 、 `hexo s` 
3. 本地浏览，未生效（尝试过在无痕模式中打开 http://localhost:4000/）

### Node.js and NPM Information | Node.js 和 NPM 信息

```Text
node -v  ： v20.15.0
npm -v ：10.7.0
```

### Hexo Configuration | Hexo 配置

```YAML
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 龚东海的博客
subtitle: 
description: ''
keywords:
author: Donghai Gong
language: zh-CN  # en | zh-CN | zh-TW
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
```

### Keep Configuration | Keep 配置

```YAML
base_info:
  # primary_color 用于设置博客网站的主题颜色，支持 十六进制、rgb 和 rgba 颜色格式
  primary_color: "#0066cc"

  # title 用于设置博客网站的标题，显示在网站的头部
  title: Donghai's Blog

  # 用于设置博客网站的作者昵称，显示在 网站底部、文章内容页 和 版权信息
  author: Donghai Gong

  # 用于设置博客网站的作者头像，将显示在文章内容页
  # 路径：your-hexo/source/images/avatar.svg
  avatar: /images/avatar.svg

  # Website LOGO, You can use local image path or image link
  logo: /images/logo.svg

  # Website favicon, You can use local image path or image link
  favicon: /images/logo.svg
```
