### ISSUE TITLE
可以隐藏文章摘要吗？

### ISSUE THREAD

**Issue by warren6sw** [XPoet/hexo-theme-keep#402]
### Issue Checklist | Issue 检查清单

- [x] I am using Keep version `4.2.5` or later. （使用 Keep `4.2.5` 或更高版本）
- [x] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Keep documents](https://keep-docs.xpoet.cn). （已阅读 [Hexo 故障处理页面](https://hexo.io/docs/troubleshooting) 和 [Keep 文档](https://keep-docs.xpoet.cn)）
- [x] I have already searched for current [issues](https://github.com/XPoet/hexo-theme-keep/issues), which does not help me. （已搜索 [Issues](https://github.com/XPoet/hexo-theme-keep/issues)，对我没有帮助）

### Feature Request | 功能需求

可以出一个开关   配置文章摘要  是否显示吗？很久之前写的文章太多，一个个去补摘要太麻烦了。 
3.4的老版本之前可以不显示摘要，但是更新之后没找到这个摘要开关，从文章截取的内容太影响观感了，乱七八糟的。

![Image](https://github.com/user-attachments/assets/b35b3f2c-f562-4fb0-b946-95ab24fc3b4d)

**Comment by justaLoli** [comment]
如果你要隐藏【所有】文章的摘要，可以考虑通过CSS注入实现。
参考文档；https://keep-docs.xpoet.cn/basis/configuration-guide/inject.html
创建一个注入的css文件填入（此方法会同时移除摘要的上下边距）：
```css
.home-post-content {
   display: none!important;
}
```
或者（此方法会保留上下边距）：
```css
.home-post-content {
   max-height:0!important;
   overflow: hidden;
}
```
也可以使用类似方法进行更精细的调整。
