### ISSUE TITLE
能否提供文章归档页面

### ISSUE THREAD

**Issue by coderzhw** [XPoet/hexo-theme-keep#53]
找了这么久，就这个主题实在是太满意了，能否提供一下文章归档的页面呢？就是按年份列出所有文章的那种

**Comment by XPoet** [comment]
@coderzhw 

在主题配置文件 _config 可以开启该页面 Archives
```yml
menu:
  Home: /
  Archives: /archives
  # ......
```
