### ISSUE TITLE
该主题几个问题咨询

### ISSUE THREAD

**Issue by coderzhw** [XPoet/hexo-theme-keep#54]
昨晚折腾了一下这个主题，很满意，有几个小问题咨询，第一次用hexo，还不是太熟
1. social图标的定义在源文件的哪个位置改呢？我想自定义几个图标请问改哪个文件的哪段代码呢？比如后台配weibo的链接那里我配电报的链接，我想把前台展示微博的那个字体图标换成电报的，请问该怎么改呢？求教
2. 关于TOC的我想实现以下效果，就是进去的时候左边TOC默认不显示，但是显示右上角TOC那个图标，如果想展开就点击右上角图标就好了，也就是默认的不显示左侧TOC，请问该如何修改呢？
3. 我想加入百度统计的脚本js，请问这段代码在哪里加入呢？
以上问题麻烦回答下哦，多谢多谢，再次感谢开发这么好的主题

**Comment by XPoet** [comment]
@coderzhw 
1. 目前 keep 主题的图标使用 fontawesome , 你可以在 https://fontawesome.com/icons?d=gallery&m=free 查找你想要的图标，然后在 social_contac 进行配置。
```yml
social_contact:
  enable: true
  links:
    github:  
    weixin:  
    qq: 
    weibo: 
    zhihu: 
    twitter: 
    facebook: 
    email: i@xpoet.cn
```

![image](https://user-images.githubusercontent.com/24516169/105822097-9917cf00-5ff6-11eb-8e84-3ae256a562f0.png)

例如你要增加 apple 图标，按上面格式增加即可。

你第一次接触 hexo ，直接改源文件对你来说会比较耗时
