### ISSUE TITLE
可以加一个更改字体的功能吗

### ISSUE THREAD

**Issue by ghost** [XPoet/hexo-theme-keep#68]
如题，可以加一个更改字体的功能吗

**Comment by XPoet** [comment]
😺 安排，纳入计划中了

**Comment by miranquil** [comment]
催更～～

**Comment by 0x7cf-k** [comment]
**催更~~ +1**

**Comment by XPoet** [comment]
该需求已在 `v3.4.9` 实现，请使用最新版本
```yml
style:
  # Font size, customize font size. (you don't usually have to fill)
  # e.g. font_size: 18px
  font_size:

  # Font family, customize font family. (you don't usually have to fill)
  # e.g. font_family: STKaiti, STSong, STHeiti
  font_family: STKaiti, STSong, STHeiti # 楷体、宋体、黑体
```
