### ISSUE TITLE
Azure Static Website部署url跳转的问题

### ISSUE THREAD

**Issue by Asinta** [XPoet/hexo-theme-keep#71]
你好，很喜欢keep这个主题，在本地搭建起来没有任何问题，但是我的hexo博客部署在Azure Static Website上。在category页面上点击某个category跳转会报404，对比本地的跳转，发现这个跳转URL是不同的：
- Azure上：
![image](https://user-images.githubusercontent.com/52993526/110211160-47eddb80-7ed0-11eb-9635-90537286325b.png)

- 本地：
![image](https://user-images.githubusercontent.com/52993526/110211189-63f17d00-7ed0-11eb-8677-29efe4121985.png)

在Azure上，如果是从主页或者某篇文章的目录图标那里点击，能正确跳转到目录详情页，请求：
![image](https://user-images.githubusercontent.com/52993526/110211279-e67a3c80-7ed0-11eb-8377-7e714aa7bd91.png)

文章详情内部的链接：
![image](https://user-images.githubusercontent.com/52993526/110211913-cdbf5600-7ed3-11eb-817e-8c0fbecd5264.png)
![image](https://user-images.githubusercontent.com/52993526/110211927-db74db80-7ed3-11eb-8c16-f6c58bc18131.png)

目录列表页生成的链接：
![image](https://user-images.githubusercontent.com/52993526/110211947-fe06f480-7ed3-11eb-876b-3ffdbdb5a0bf.png)
![image](https://user-images.githubusercontent.com/52993526/110211957-0828f300-7ed4-11eb-8089-48acd8102f5b.png)

像是使用相对路径生成href的问题，但是我不知道要在哪改，请帮忙看一下这个问题，谢谢！

**Comment by Asinta** [comment]
@XPoet 麻烦大佬帮忙看一下，看起来像是因为Azure托管的静态站点现在解析href都是默认从/开始的，而不是用的文件系统的层次结构，所以本地没问题，一部署上去就出现上述的问题。所以我理解如果目录列表页的href也是绝对路径`categories/NET-Core`应该就修复了，然而我只在这里：
![image](https://user-images.githubusercontent.com/52993526/110212275-95207c00-7ed5-11eb-8b8e-d676e4bffac5.png)
看到了生成这段代码的地方，但是不清楚要怎么修改。。。前端小白

**Comment by XPoet** [comment]
请提供：
1. 你部署在 Azure 上的网址
2. 你的 Hexo 配置文件 `_config.yml`

**Comment by Asinta** [comment]
地址：https://www.code4nothing.cn
hexo 配置：
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Code4Nothing
subtitle:
description: WRITING CODE & TELLING STORIES
keywords:
author: Asinta
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://www.code4nothing.cn/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
search:
  path: search.json
  field: post
  content: true
  format: striptags
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

jsonContent:
  meta: true
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: true
    link: false
    permalink: true
    excerpt: false
    categories: true
    tags: true
    thumbnail: true
    color: false
    sticky: true
    toc: true
```
