### ISSUE TITLE
部署到 Gitee Pages 上之后某些资源无法显示

### ISSUE THREAD

**Issue by yrylalala** [XPoet/hexo-theme-keep#77]
由于 github 比较难被搜索引擎收录，就尝试将博客同时部署到 Gitee 上，
但是部署完之后，发现部分 css 资源无法访问到了。
![image](https://user-images.githubusercontent.com/29858901/112635935-60ba3300-8e77-11eb-9d3b-365ed78a4761.png)

官方是这样解释的
![image](https://user-images.githubusercontent.com/29858901/112636005-792a4d80-8e77-11eb-92b7-3f1f64dbb883.png)

于是我在我本地根目录下的 `_config.yml` 中做了配置修改
![image](https://user-images.githubusercontent.com/29858901/112636451-11283700-8e78-11eb-8384-bd9d8daf9a5e.png)
![image](https://user-images.githubusercontent.com/29858901/112635783-35374880-8e77-11eb-9588-2bbceb0eb3a8.png)

但是还是无法生效
所以这里想问一下，`url` 和 `root` 这两个配置项是在根目录的下 `_config.yml` 中做配置吗？还是在主题下的 `_config.yml` 做配置？
这两个文件是有覆盖的情况吗？

**Comment by XPoet** [comment]
请提供：
1. 你的 gitee 仓库地址，gitee pages 地址
2. Hexo 配置文件

**Comment by yrylalala** [comment]
gitee 仓库地址:
https://gitee.com/yrylalala/blog.git

gitee pages 地址
https://yrylalala.gitee.io/blog

本地根目录下的 Hexo 配置文件 `./MyBlog/yrylalala/_config.yml`  

<details>
<summary>_config.yml</summary>

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://yrylalala.gitee.io/blog
root: .
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: keep

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 
    github: git@github.com:yrylalala/yrylalala.github.io.git
    gitee: git@gitee.com:yrylalala/blog.git
  branch: main
```
</details>  


主题目录下的配置文件 `./MyBlog/yrylalala/node_modules/hexo-theme-keep/_config.yml`  
<details>
<summary>_config.yml</summary>  

```yml
# ---------------------------------------------------------------------------------------
#  Your basic info
# ---------------------------------------------------------------------------------------
base_info:
  title: 笃志
  author: yrylalala
  url: https://yrylalala.github.io/


# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: '#0066CC'

  # Avatar (You can use local image or image external link)
  avatar: /images/MyPhoto.jpeg

  # Favicon (You can use local image or image external link)
  favicon: /images/logo.svg

  # Article image align position, value: left | center
  article_img_align: left

  # Left side width
  left_side_width: 260px

  # Content area max width
  content_max_width: 920px

  # Mouse hover
  hover:
    shadow: false   # shadow effect when the mouse hover
    scale: true    # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_img: /images/bg.svg   # You can use local image or image external link
    description: "生而为人，你且修身，你且渡人，你且如水，居恶渊而为善，无尤也。"

  # Scroll style settings
  scroll:
    progress_bar:
      enable: false
    percent:
      enable: false


# ---------------------------------------------------------------------------------------
# Social contact link
# ---------------------------------------------------------------------------------------
social_contact:
  enable: false
  links:
    github:          # your GitHub URL
    weixin:          # your WeChat QR-Code URL
    qq:              # your QQ QR-Code URL
    weibo:           # your WeiBo URL
    zhihu:           # your ZhiHu URL
    twitter:         # your twitter URL
    facebook:        # your facebook URL
    email:           # your email


# ---------------------------------------------------------------------------------------
# Navigation menu
# ---------------------------------------------------------------------------------------
menu:
  首页: /
  归档: /archives
  分类: /categories
  标签: /tags
  # Home: /
  # Archives: /archives
  # Categories: /categories
  # Tags: /tags
  # Links: /links
  # About: /about
  # Changelog: /changelog
  # ......


# ---------------------------------------------------------------------------------------
# Home page article block display settings
# ---------------------------------------------------------------------------------------
home_article:
  category:
    enable: true     # show category in home page article block
    limit: 3          # max number of categories shown in home page article block
  tag:
    enable: true     # show tags in home page article block
    limit: 5          # max number of tags shown in home page article block


# ---------------------------------------------------------------------------------------
# Post page Settings
# ---------------------------------------------------------------------------------------
post:
  # Post word count
  # Dependencies: hexo-wordcount (npm install hexo-wordcount)
  # See: https://github.com/willin/hexo-wordcount
  word_count:
    enable: false
    wordcount: false  # word count, one article
    min2read: false   # time to read, one article

  # Author label
  author_label:
    enable: true
    auto: true  # if true, show Lv1, Lv2, Lv3... , If false, show custom label
    # label array item can be one or more
    custom_label_list: [ "Trainee", "Engineer", "Architect", "CTO", "BOSS" ]


# ---------------------------------------------------------------------------------------
# Code copy
# ---------------------------------------------------------------------------------------
code_copy:
  enable: false
  style: default        # values: default | mac


# ---------------------------------------------------------------------------------------
# Table of Contents in the Sidebar
# ---------------------------------------------------------------------------------------
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: false

  # If true, open TOC every time when you enter the article page
  init_open: false


# ---------------------------------------------------------------------------------------
# Post copyright info
# ---------------------------------------------------------------------------------------
copyright_info:
  enable: false


# ---------------------------------------------------------------------------------------
# Website count
# ---------------------------------------------------------------------------------------
website_count:
  # busuanzi
  # See: http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: true
    site_pv: true
    page_pv: true


# ---------------------------------------------------------------------------------------
# Local Search
# Dependencies: hexo-generator-searchdb
# See: https://github.com/theme-next/hexo-generator-searchdb
# ---------------------------------------------------------------------------------------
local_search:
  enable: true
  preload: false     # Preload the search data when the page loads


# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: false
  use: valine  # values: valine | gitalk | twikoo

  # Valine
  # See: https://github.com/xCss/Valine
  valine:
    appid:                # your leancloud application appid
    appkey:               # your leancloud application appkey
    placeholder:          # your placeholder

  # Gitalk
  # See: https://github.com/gitalk/gitalk
  gitalk:
    github_id:             # GitHub repo owner
    repository:            # Repository name to store issues
    client_id:             # GitHub Application Client ID
    client_secret:         # GitHub Application Client Secret

  # Twikoo
  # See: https://github.com/imaegoo/twikoo
  twikoo:
    env_id:                # Tencent Cloud environment id
    region:                # environment region. If select Guangzhou, fill in "ap-guangzhou".


# ---------------------------------------------------------------------------------------
# RSS
# Dependencies: hexo-generator-feed
# See: https://github.com/hexojs/hexo-generator-feed
# ---------------------------------------------------------------------------------------
rss:
  enable: false


# ---------------------------------------------------------------------------------------
# Lazyload image
# ---------------------------------------------------------------------------------------
lazyload:
  enable: false


# ---------------------------------------------------------------------------------------
# CDN
# ---------------------------------------------------------------------------------------
cdn:
  enable: false


# ---------------------------------------------------------------------------------------
# PJAX
# ---------------------------------------------------------------------------------------
pjax:
  enable: false


# ---------------------------------------------------------------------------------------
# Footer settings
# ---------------------------------------------------------------------------------------
footer:
  since: 2020      # the starting year of your website, Can be null
  icp:             # ICP record number of your website, Can be null


# ---------------------------------------------------------------------------------------
# Keep version (Please don't modify)
# ---------------------------------------------------------------------------------------
version: 3.4.1
```
</details>  

所有代码当前在 coding 上可以看到
https://e.coding.net/yrylalala/blog/MyBlog.git

**Comment by XPoet** [comment]
针对你反馈的问题，经过作者排查，已修复主题资源引用路径的错误，请使用最新版本 `v3.4.2`，然后重新编译和部署 Gitee Pages

根据你的情况，你的 Hexo 配置文件的 root 设置为 `/blog`

```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://yrylalala.gitee.io/blog
root: /blog
```

**Comment by yrylalala** [comment]
**非常感谢作者及时支持！！！**

当前还有部分小问题  
关于图片的显示，现在的背景图片路径和 logo 的图片路径配置方式有差异
_config.yml 文件
```yml
# ---------------------------------------------------------------------------------------
# Theme style settings
# ---------------------------------------------------------------------------------------
style:
  # Theme primary color
  primary_color: '#0066CC'

  # Avatar (You can use local image or image external link)
  avatar: /images/MyPhoto.jpeg

  # Favicon (You can use local image or image external link)
  favicon: /images/logo.svg

  # Article image align position, value: left | center
  article_img_align: left

  # Left side width
  left_side_width: 260px

  # Content area max width
  content_max_width: 920px

  # Mouse hover
  hover:
    shadow: false   # shadow effect when the mouse hover
    scale: true    # scale effect when the mouse hover

  # First screen
  first_screen:
    enable: true
    background_img: /images/bg.svg   # You can use local image or image external link
    description: "生而为人，你且修身，你且渡人，你且如水，居恶渊而为善，无尤也。"

  # Scroll style settings
  scroll:
    progress_bar:
      enable: false
    percent:
      enable: false
```

背景图片访问失败  
![image](https://user-images.githubusercontent.com/29858901/112991558-d7b63b00-9199-11eb-8341-d12bafd71538.png)


logo 图片访问成功  
![image](https://user-images.githubusercontent.com/29858901/112991826-25cb3e80-919a-11eb-9ddc-0cb80b223a7f.png)

**Comment by XPoet** [comment]
Keep 主题单独把 `avatar`、`favicon`、`background_img` 抽离开配置项，是想让用户设置更灵活一些，比如这几个配置项，你除了可以使用本地图片外，还可以使用图片外链。

根据你的情况，在以下几个配置项值的前面加上 `/blog` 即可访问到该图片资源。

```yaml
avatar: /blog/images/MyPhoto.jpeg
favicon: /blog/images/logo.svg
background_img: /blog/images/bg.svg   
```
