### ISSUE TITLE
怎么更改主题颜色

### ISSUE THREAD

**Issue by StevenChaoo** [XPoet/hexo-theme-keep#78]
默认主题颜色是#0066cc，我想改成白色主题，于是把数值改成了#ffffff，但是重新部署后颜色没有变化

**Comment by XPoet** [comment]
在 Keep 主题配置文件里设置
```yaml
style:
  # Theme primary color
  primary_color: "#0066CC"
```

颜色值需带上双引号，例如："#00CC33"


请勿设置成 "#ffffff" 纯白色，因为主题本身就是纯白偏多，再将 primary_color 设置成纯白色，体验会非常差！

如果你在本地跑的 Hexo，主题颜色改成功了，部署后一样会成功的！请清空一下浏览器缓存，再刷新看看
