### ISSUE TITLE
关于description文字换行的问题

### ISSUE THREAD

**Issue by jacksparrow414** [XPoet/hexo-theme-keep#97]
在首屏的description选项中，如果想要展示多行文字，应该怎么写呢？
description: a, b
想要的首屏效果是：
a,
b
而不是a,b
 使用\n，|， |+都未能实现段落效果

**Comment by XPoet** [comment]
@jacksparrow414  目前不支持换行，后续版本再加上

**Comment by jacksparrow414** [comment]
好的，感谢. 😃

**Comment by Learner110110** [comment]
我有同样的需求，我不是前端程序员，艰难地看了一下代码，貌似是first-screen.ejs文件中第4行的"<%= theme.style.first_screen.description || config.description %>"这里处理的，查了一下ejs中<%= %>会转义处理，<%- %>不转义处理，不知道是否是因为安全性的考虑

**Comment by XPoet** [comment]
@jacksparrow414 
@Learner110110 
Keep 主题 v3.5.0 即将发布，首屏描述将会支持换行，换行符 ` ||`

**Comment by XPoet** [comment]
Keep 主题 v3.4.6 已支持该功能，请使用最新版本。

```
npm install hexo-theme-keep@3.4.6
```

```
  # First screen style settings
  first_screen:
    enable: true # Option values: true | false

    # First screen description
    # You can use the "||" to begin a newline, maximum is two lines.
    description: Keep writing and Keep loving. || this is a test sentence
```
